name: Feature Request
description: Suggest a new feature or enhancement
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe what you'd like and why it would be useful.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature or enhancement you'd like.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What does "done" look like? List concrete, testable criteria.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, mockups, or examples.
    validations:
      required: false
